### ISSUE TITLE
Unresolved requirement: Import-Package: org.openhab.core.binding

### ISSUE THREAD

**Issue by Tompie500** [docbender/openHAB-Simatic#13]
Hi,
I have following error in my log file:
2019-12-28 20:43:15.897 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/C:/Program%20Files/OpenHab/addons/org.openhab.binding.simatic-1.14.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.simatic [222]
  Unresolved requirement: Import-Package: org.openhab.core.binding
Also, with the command:
openhab> list | grep -i binding
136 │ Active    │  80 │ 2.5.0                   │ openHAB Core :: Bundles :: Binding XML
211 │ Active    │  80 │ 2.5.0                   │ openHAB Add-ons :: Bundles :: hue Binding
215 │ Active    │  80 │ 2.5.0                   │ openHAB Add-ons :: Bundles :: Network Binding
222 │ Installed │  80 │ 1.14.0.201911280848     │ openHAB Simatic Binding
I see the Simatic binding is installed but not running. 

Can somebody help me out please?
Thanks,
Tom.

**Comment by docbender** [comment]
Probably problem with binding 1.x compatibility layer. Now OH3 binding is available
