### ISSUE TITLE
Channel as chButton... OH3

### ISSUE THREAD

**Issue by grzegorz914** [docbender/openHAB-Simatic#21]
Hi,

it is possible that U add as type of channel **chButton** which will be send after button press commands ON(1) and OFF(0).
Right now I need to create for every button input extra rule in OH to send this two commands.

**Comment by docbender** [comment]
Hi, I do not know about channel type button. Is it some undocumented type or function? I found only information about [string command that could be rendered as push button](https://www.openhab.org/docs/developer/bindings/thing-xml.html#command-description).
If you need to reset your command, why not do it in PLC?

**Comment by grzegorz914** [comment]
Hmm,
U are right , I can doit this in PLC.

Nice Tip Thanks
