### ISSUE TITLE
OH3.0 add to the add-on repo....

### ISSUE THREAD

**Issue by grzegorz914** [docbender/openHAB-Simatic#22]
Hi,

are U plan to add the simatic-binding to the add-on repo of OH3.0?

**Comment by docbender** [comment]
Right now no. Last time I tried, it takes half year till somebody contact me and revision process dragged so long. And preparation (clean code) takes lot of time (no warnings, every file must have their header, every method must have comment,... )

**Comment by grzegorz914** [comment]
OK, all clear
