### ISSUE TITLE
Feature request Unit

### ISSUE THREAD

**Issue by grzegorz914** [docbender/openHAB-Simatic#28]
Hi,
can U add to The Things Channel possibility to set **Unit** for Number value?
For example The possibility is already implemented in **http binding**

Thanks

**Comment by docbender** [comment]
It is possible. For Number channel I will add parameter Unit. If this parameter is filled, value will be post into OH as QuantityType

**Comment by grzegorz914** [comment]
Ok,

Thanks

**Comment by docbender** [comment]
Released in 3.0.5. Channel Number has now additional parameter _unit_
