### ISSUE TITLE
Rollershutter state 

### ISSUE THREAD

**Issue by Maddin2020** [docbender/openHAB-Simatic#31]
Hi docbender,

thanks for support. Now i have a problem with my Rollerschutter.

I have define this Things for Rollershutter and i can see the 2 for Stop, 4 for UP and 8 for down. But i don´t understand the StateAdress. How i can see the State. If i write to the stateadress from PLC nothing happend. 

Can you help me ?

Things:

`Type chRollershutter: Jalousie              "Jalousie Steuerung"            [ stateAddress="DB2001.DBB1106",commandAddress="DB2001.DBB1107" ]`

**Comment by docbender** [comment]
Hi. 
State only return actual percentage position. What exactly you expected? I don't use rollershutter.  So I'm not familiar with GUI behavior. Should the behavior of binding be different?
