### ISSUE TITLE
Can not write byte, word, dword, float

### ISSUE THREAD

**Issue by MFI-Net** [docbender/openHAB-Simatic#32]
Hi,

I also want to write byte, word, dword, float variables in the PLC system. For a bit variable it no problem. But all other are not working.

example: 

Type chNumber: SPS_S7_Heizung_Prozent_absenken_Urlaub [ stateAddress="DB3.DBW106" ]  

also tested:
Type chNumber: SPS_S7_Heizung_Prozent_absenken_Urlaub [ stateAddress="DB3.DBW106", commandAddress="DB3.DBW106" ] 

ITEM: 
Number        SPS_S7_Heizung_Prozent_absenken_Urlaub  "Prozent absenken [%d]"    {channel="simatic:generic_device:S7-300:Energie:SPS_S7_Heizung_Prozent_absenken_Urlaub"}

Any advice??

Thanks in advanc
Martin

**Comment by docbender** [comment]
Hi,
PLC reading works? If so, try looking at openHAB log for errors. 
However, a _commandAddress_ parameter must be defined for writing data from OH into PLC.
