### ISSUE TITLE
write a DoubleWord in the PLC, it seems that High and Low words are reversed.

### ISSUE THREAD

**Issue by MFI-Net** [docbender/openHAB-Simatic#35]
Hi,

if I write a Doubleword in the PLC, it seems that High and Low words are reversed.

sample:    Type chNumber: SPS_S7_300_Set_Uhrzeit [ stateAddress="DB1.DBD132", commandAddress="DB1.DBD132"]
State Adress is correct. 
rule:

 var Number x = SPS_S7_300_Set_Uhrzeit .state  
// when I now sent the same value back:
 SPS_S7_300_Set_Uhrzeit .sendCommand(x)

than the value  (DBD132  )  of DW 132 is in DW 134 and DW134 in DW132

Best regards
Martin

**Comment by docbender** [comment]
Hi,
I wrote from OH value into double word and the same value is also in the PLC:
![image](https://user-images.githubusercontent.com/10372334/145235619-5b89d729-b504-413d-8a4e-45ad630101ab.png)

Simatic PLCs are Big-Endian. Different byte order is normal behavior. If you want to write by individual bytes or words, then their order must be respected when writing.
