### ISSUE TITLE
I can´t read the Data Type Time from PLC

### ISSUE THREAD

**Issue by Maddin2020** [docbender/openHAB-Simatic#36]
Hello Docbender,

i want read a value with the Datatype "Time" from the PLC (32 bit). Example i want read the actual Time Value from a IEC Timer. Then i have connect the Data Point DB2001.DBD3028  in the Things Data Table. I only received 0 in the value Dammerung_Restzeitms.

All other data Points working correctly. 

```
 Thing generic_device gobal {
        Channels:                          
            Type chNumber: Dammerung_Restzeitms         "Dämmerung Restzeit"            [ stateAddress="DB2001.DBD3028"]
    }
``` 

Thanks a lot for your support and thank for the great binding. 

Martin

**Comment by docbender** [comment]
Hi,
isn't problem in address "DB2001.DBW3028"? It should be DBDxx instead DBWxx. Right?

19. 12. 2021 17:21, 17:21, Maddin2020 ***@***.***> napsal/a:

**Comment by Maddin2020** [comment]
Hey docbender yes DBxxx.DBD is right because the data Type "Time" have 32 Bit. If i change the data Type in "DInt" then it work but i don't understand the reason because the  length is the same. I think you know that the data type Time is only the value in Milli seconds. If i select Time data Type in the Tia Portal i can read it easilier.

**Comment by docbender** [comment]
Data are read as byte array. I have no idea why it is read as zero. If you read DBD address with whatever type on Simatic side, on binding side have to be data stored in that 4 bytes (number of millisecond in this case).
As a workaround I would use a transfer in code:
```
 L    TIME_VARIABLE
 T    DINT_VARIABLE
```

**Comment by Maddin2020** [comment]
Thanks again for answer. Ok i will use this workaround. Do you have the same Issue if you Test it on your plc ?

**Comment by docbender** [comment]
With S7-400 no problem
![image](https://user-images.githubusercontent.com/10372334/146907061-5c3775b5-be59-4a40-a935-13d1dd87e06f.png)
