### ISSUE TITLE
Binding stop working if Mail Action remove

### ISSUE THREAD

**Issue by grzegorz914** [docbender/openHAB-Simatic#4]
Hello,

I have strange problem, after remove Mail Action from openHAB simatic bindings stop working with error:

> 2018-02-19 16:22:54.128 [ERROR] [org.openhab.binding.simatic         ] - FrameworkEvent ERROR - org.openhab.binding.simatic
> org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.simatic [222]
>   Unresolved requirement: Import-Package: org.openhab.core.binding
> 	at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620) [?:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1600) [?:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571) [?:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514) [?:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [?:?]
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]

after install Mail Action again ,simatic start working correct.

**Comment by docbender** [comment]
For me it looks like _Mail Action_ issue or even OH2 issue. When u uninstall it, org.openhab.core.binding dependency package is missing. It can not happen if there exists a package which need it (which is SIMATIC)

**Comment by grzegorz914** [comment]
Ok,

Thanks
