### ISSUE TITLE
Value don't Update

### ISSUE THREAD

**Issue by Maddin2020** [docbender/openHAB-Simatic#45]
Hi docbender First big thanks for your work i use the Binding for openhab for a Long Time. Now i have a Little Problem with the Binding. Some value don't Update. But If i Teach the value from
Openhab the value change but If i change the value in the sps it don't change in openhab. Can you give ne a tip why ?

**Comment by docbender** [comment]
If commands are OK, it could be an unset state address. Is something in log?

6. 3. 2023 22:58, 22:58, Maddin2020 ***@***.***> napsal/a:
