### ISSUE TITLE
O.H. 4.0 (Unit) number channel with command address and unit is not updated

### ISSUE THREAD

**Issue by grzegorz914** [docbender/openHAB-Simatic#46]
Hi,

after latest update in O.H. 4.x and support default unit for Number the channels which uses command address and unit are not updated anymore, always return 0. After remove unit all working correct.
Linked item is Number Dimensionless 

![IMG_0841](https://github.com/docbender/openHAB-Simatic/assets/28867813/71a0414c-66d9-4a23-8000-88ba980d576b)

Thanks
Grzegorz

**Comment by docbender** [comment]
It is working for me.  

Isn't the problem that OH now displays percentages in the range 0-1? Received values are divided by 100. So OH displays 1, if PLC value is 100.

**Comment by grzegorz914** [comment]
Yes, that was the problem, my Channels are 0-100%.

**Comment by docbender** [comment]
Set items metadata to unit = %, then OH displays values as 0-100.
